
services:
  db:
    image: postgres:latest
    container_name: triagemcheck-db
    environment:
      POSTGRES_DB: triagemcheck
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: C:/Users/marco/OneDrive/Projects/TriagemCheck
      dockerfile: Dockerfile
    container_name: triagemcheck-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/triagemcheck
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8082:8082"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local